### ISSUE TITLE
How does this compare to Data.Strict?

### ISSUE THREAD

**Issue by 3noch** [factisresearch/strict-data#1]
https://hackage.haskell.org/package/strict

**Comment by agrafix** [comment]
Basically the names don't clash with prelude.

**Comment by 3noch** [comment]
Any reason you didn't just depend on `strict` and export aliases?

**Comment by agrafix** [comment]
It might not be a bad idea from the perspective to be compatible with projects already using `strict`, on the other hand we would have to write some orphan instances

**Comment by 3noch** [comment]
Should they just be part of `strict` anyway? In which case you could submit them in PR.

**Comment by agrafix** [comment]
Maybe, for now I'm not sure where this package is going so for now I'd rather have this as a separate package under my full control and maybe merge later.

**Comment by 3noch** [comment]
Sounds good. If I end up using `strict` more I might import some of your instances as a PR.

**Comment by agrafix** [comment]
Sure :-)
